In [ ]:
import tensorflow as tf


In [ ]:
tf.ones([10,2])

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
#create a tesnor of all zeros
tf.zeros(shape=(10, 2))

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
#convert numpy arrays to tensorflow tensors
import numpy as np

# capital for matrix or tensor

numpy_A = np.arange(1,25,dtype=np.int32)

In [ ]:
A = tf.constant(numpy_A,shape = (3,1,2,2,1,2))
A

<tf.Tensor: shape=(3, 1, 2, 2, 1, 2), dtype=int32, numpy=
array([[[[[[ 1,  2]],

          [[ 3,  4]]],


         [[[ 5,  6]],

          [[ 7,  8]]]]],




       [[[[[ 9, 10]],

          [[11, 12]]],


         [[[13, 14]],

          [[15, 16]]]]],




       [[[[[17, 18]],

          [[19, 20]]],


         [[[21, 22]],

          [[23, 24]]]]]], dtype=int32)>

In [ ]:
A.ndim

6

# Getting information from tesnors TENSOR ATTRIBUTES
* shape
* Rank
* Axis,Dimensions
*Size




In [ ]:
# Create a rank 4 tesnor

rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
tf.size(rank_4_tensor) # 2*3*4*5 = 120 elements

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
#Get various attributes of a tensor
print("Datatype of every element:0",rank_4_tensor.dtype)
print("Number of dimensions are :",rank_4_tensor.ndim)
print("Shape of the tensor",rank_4_tensor.shape)
print("Elements along 0 axis",rank_4_tensor.shape[0])
print("Elemet alog alst axis",rank_4_tensor.shape[-1])
print("Total number of lelements in tensor",tf.size(rank_4_tensor).numpy())

Datatype of every element:0 <dtype: 'float32'>
Number of dimensions are : 4
Shape of the tensor (2, 3, 4, 5)
Elements along 0 axis 2
Elemet alog alst axis 5
Total number of lelements in tensor 120


*italicized text*#### Indexing tensors
Get the foirst 2 elements


In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get each element from each index except for the final one
rank_4_tensor[:1,:,:1,:]


<tf.Tensor: shape=(1, 3, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
 #Create a rank 2 tensor
 rank_2_tensor = tf.constant([[10,20],[30,40]])
 rank_2_tensor.shape, rank_2_tensor.ndim,rank_2_tensor


(TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>)

In [ ]:
#get last item of the above tensor
rank_2_tensor[:,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
 rank_2_tensor[:1,:]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10, 20]], dtype=int32)>

In [ ]:
#Add extra dimension
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_3_tensor,axis =-1)

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[20]]],


       [[[30]],

        [[40]]]], dtype=int32)>

In [ ]:
 #Add extra dimension
rank_3_tensor = tf.expand_dims(rank_3_tensor,axis =-1)
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[20]]],


       [[[30]],

        [[40]]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis =1)


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10, 20]],

       [[30, 40]]], dtype=int32)>

#Manipulating tensors
Basic operations + - * /


In [ ]:
tensor = tf.constant([[10,7],
                     [3,4]])

In [ ]:
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor*10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#Use tensorflow built in function
tf.multiply(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
tf.add(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]], dtype=int32)>

## Matrix Multiplication
http://matrixmultiplication.xyz/

https://www.mathsisfun.com/algebra/matrix-multiplying.html

* Most common used operation in machine learning

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:

np.dot(tensor,tensor)

array([[121,  98],
       [ 42,  37]], dtype=int32)

In [ ]:
x= tf.constant([[3,4],[5,6],[7,8]])
x.shape

TensorShape([3, 2])

In [ ]:
y = tf.constant([[7,7],[11,12],[9,10]])
y.shape

TensorShape([3, 2])

There are 2 rules to follow for matrix multiplication
1. the inner dimensions must match
2. the resulting matrix has the shape od the inner dimensions

In [ ]:
y_T = tf.transpose(y)
y_T
x.shape,y_T.shape


(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
z = tf.matmul(x,y_T)
z,z.shape

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 49,  81,  67],
        [ 77, 127, 105],
        [105, 173, 143]], dtype=int32)>,
 TensorShape([3, 3]))

In [ ]:
x@y_T

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 49,  81,  67],
       [ 77, 127, 105],
       [105, 173, 143]], dtype=int32)>

In [ ]:
tf.tensordot(x,y_T,axes=1)
y.shape


TensorShape([3, 2])

In [ ]:
tf.matmul(tf.reshape(x,shape=(2,3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 119],
       [191, 206]], dtype=int32)>

Changing Data types of tensors

Create new tesnor with default datatype



In [ ]:
B= tf.constant([10.,7.]) ##float32
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>

In [ ]:
A = tf.constant([10,7]) ## integer

In [ ]:
#change from float 32 to float 16
tf.cast(B, dtype=tf.float16) ##float16


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.,  7.], dtype=float16)>

In [ ]:
tf.cast(A, dtype=tf.float32
) ##float16


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>

In [ ]:
### Aggregating Tensors


In [ ]:
S = tf.constant([-10,-7])
S

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10,  -7], dtype=int32)>

In [ ]:
tf.abs(S)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(1,100, size=50))

In [ ]:
E.shape, E.ndim,tf.size(E)
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([38,  8, 20,  7, 58, 56, 83, 47, 45, 63, 33,  2, 68,  1, 60, 83, 36,
       47, 67, 82,  3,  3, 47,  6, 70, 86, 73, 55, 50, 53, 19, 53, 36, 23,
       22, 88, 57, 52, 34, 81, 97, 38, 72, 19, 91, 31, 51, 95, 12, 82])>

In [ ]:
tf.reduce_min(E) #min

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.reduce_max(E) #max

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_mean(E) #mean

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2403>

In [ ]:
E = tf.cast(E,dtype = tf.float16)
tf.math.reduce_std(E) # standadrd deviation

<tf.Tensor: shape=(), dtype=float16, numpy=27.66>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(E)  #variance

<tf.Tensor: shape=(), dtype=float16, numpy=765.0>

In [ ]:
tf.argmax(E) # positional maximum

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [ ]:
tf.argmin(E) # positional minimum

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

SQUEEZING A TENSOR

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform (shape = [50]),shape = (1,1,1,1,50))

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape,G_squeezed

(TensorShape([50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)

## One hot encoding Tensors

In [ ]:
list = [0,1,2,3,4]

tf.one_hot(list,depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(list,depth=5, on_value ="True",off_value="False")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'True', b'False', b'False', b'False', b'False'],
       [b'False', b'True', b'False', b'False', b'False'],
       [b'False', b'False', b'True', b'False', b'False'],
       [b'False', b'False', b'False', b'True', b'False'],
       [b'False', b'False', b'False', b'False', b'True']], dtype=object)>


Square , log , square root

In [ ]:
 H = tf.range(1,10)

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Lets find the square
tf.sqrt(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#Tensors and NUmpy

In [ ]:
#Create a tesnor from numpy array

J = tf.constant(np.array([3,4,5,6,]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 4, 5, 6])>

In [ ]:
np.array(J),type(np.array(J))

(array([3, 4, 5, 6]), numpy.ndarray)

In [ ]:
#Convert tensor to numpy another way
J.numpy()

array([3, 4, 5, 6])

In [ ]:
#default types numpy creates 64 while tenssor creates 32bit

numpy_J = tf.constant(np.array([3,4,5,6]))
tensor_J = tf.constant([3,4,5,6])
#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.int64, tf.int32)

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]